/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PadresRouteImport } from './routes/padres'
import { Route as QuioscoRouteImport } from './routes/quiosco'
import { Route as ReportesRouteImport } from './routes/reportes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PadresRoute = PadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => rootRouteImport,
} as any)
const QuioscoRoute = QuioscoRouteImport.update({
  id: '/quiosco',
  path: '/quiosco',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/padres': typeof PadresRoute
  '/quiosco': typeof QuioscoRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/padres': typeof PadresRoute
  '/quiosco': typeof QuioscoRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/padres': typeof PadresRoute
  '/quiosco': typeof QuioscoRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/padres' | '/quiosco' | '/reportes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/padres' | '/quiosco' | '/reportes'
  id: '__root__' | '/' | '/padres' | '/quiosco' | '/reportes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PadresRoute: typeof PadresRoute
  QuioscoRoute: typeof QuioscoRoute
  ReportesRoute: typeof ReportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padres': {
      id: '/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof PadresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiosco': {
      id: '/quiosco'
      path: '/quiosco'
      fullPath: '/quiosco'
      preLoaderRoute: typeof QuioscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PadresRoute: PadresRoute,
  QuioscoRoute: QuioscoRoute,
  ReportesRoute: ReportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
